# Generated by Django 5.1.3 on 2025-02-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autores', models.AutoField(primary_key=True, serialize=False)),
                ('aut_nome', models.CharField(max_length=75)),
                ('aut_nacionalidade', models.CharField(max_length=20)),
                ('aut_biografia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liv_titulo', models.CharField(max_length=200)),
                ('liv_ISBN', models.CharField(max_length=13)),
                ('liv_edicao', models.CharField(max_length=50)),
                ('liv_editora', models.CharField(max_length=100)),
                ('liv_ano_publicacao', models.IntegerField()),
                ('liv_preco_capa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('liv_categoria', models.CharField(max_length=100)),
                ('liv_quant', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papelaria.autor')),
            ],
            options={
                'db_table': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_entrada', models.DateField()),
                ('est_saida', models.DateField()),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papelaria.livros')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venda', models.IntegerField(default=0)),
                ('ven_quant_vendida', models.IntegerField(default=0)),
                ('ven_data_venda', models.DateField()),
                ('ven_valor', models.FloatField(default=0)),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papelaria.livros')),
            ],
        ),
    ]
