# Generated by Django 5.1.3 on 2025-02-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papelaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroAutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Papelaria.autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Papelaria.livro')),
            ],
            options={
                'unique_together': {('livro', 'autor')},
            },
        ),
        migrations.AlterField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(through='Papelaria.LivroAutores', to='Papelaria.autor'),
        ),
    ]
